apiVersion: apps/v1
kind: Deployment
metadata:
  name: sevenmentor-regapp
  labels:
     app: regapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: regapp

  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp 
        image: diptimokat/docker_kubernetes_project
        imagePullPolicy: Always
        ports:
        - containerPort: 8080